name: 222-CLL

permissions:
  contents: write        # for pushing JSON files
  pull-requests: write   # for opening the PR
  issues: write          # for creating/applying labels
  
on:
  workflow_dispatch:

env:
  DEPTH: 8
  MOVE_SET: "R R' R2 U U' U2 F F' F2"

jobs:
  solve:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: "1"
      TERM: xterm-256color
      NO_COLOR: false
    strategy:
      matrix:
        id: [CLL_Sune_1, CLL_Sune_2, CLL_Sune_3, CLL_Sune_4, CLL_Sune_5, CLL_Sune_6]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run solver for ${{ matrix.id }}
        run: |
          go run ./cmd config/222-CLL.csv ${{ matrix.id }} $DEPTH "$MOVE_SET"

      - name: Upload JSON results
        uses: actions/upload-artifact@v4
        with:
          # unique per-matrix name so no conflicts
          name: 222-CLL-results-${{ matrix.id }}
          path: db/222-CLL/${{ matrix.id }}.json

  pr:
    needs: solve
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Download all JSON results
        uses: actions/download-artifact@v4
        with:
          path: db/222-CLL

      - name: Create Pull Request with all results
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: |
            Update solver results for 222-CLL (depth ${{ env.DEPTH }})
          title: Update solver results for 222-CLL
          body: |
            Update solver‐generated JSON outputs for the `222-CLL.csv` input at depth ${{ env.DEPTH }}.
            Includes result files for each matrix ID under `db/222-CLL/`.
          base: main
          branch: 222-CLL-results
          labels: 222-CLL-results,222-CLL
