name: 222-CLL

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:

env:
  DEPTH: 8
  MOVE_SET: "R R' R2 U U' U2 F F' F2"

jobs:
  solve:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        id: [CLL_Sune_1, CLL_Sune_2, CLL_Sune_3, CLL_Sune_4, CLL_Sune_5, CLL_Sune_6]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run solver for ${{ matrix.id }}
        run: |
          go run ./cmd config/222-CLL.csv ${{ matrix.id }} $DEPTH "$MOVE_SET"

      - name: Collect results paths
        id: produce
        run: |
          echo "json-paths=db/222-CLL/${{ matrix.id }}.json" >> $GITHUB_OUTPUT

  pr:
    needs: solve
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Create Pull Request with all results
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: |
            Update solver results for 222-CLL (depth ${{ env.DEPTH }})
          title: Update solver results for 222-CLL
          body: |
            This PR contains the JSON outputs for all CLL_* runs at depth ${{ env.DEPTH }}.
          base: main
          branch: 222-CLL-results
          labels: solver-results
          add-paths: |
            db/222-CLL/*.json
