name: 222-CLL

permissions:
  contents: write        # allow us to push commits
  pull-requests: write   # allow us to open PRs

on:
  workflow_dispatch:

env:
  DEPTH: 8
  MOVE_SET: "R R' R2 U U' U2 F F' F2"

jobs:
  solve:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        id: [CLL_Sune_1, CLL_Sune_2, CLL_Sune_3, CLL_Sune_4, CLL_Sune_5, CLL_Sune_6]

    outputs:
      # expose the list of generated files so the PR job can pick them up
      results: ${{ steps.produce.outputs.json-paths }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run solver for ${{ matrix.id }}
        run: |
          go run ./cmd config/222-CLL.csv ${{ matrix.id }} $DEPTH "$MOVE_SET"

      - name: Collect results paths
        id: produce
        run: |
          # after solver, the JSON will be at db/222-CLL/${{ matrix.id }}.json
          echo "::set-output name=json-paths::db/222-CLL/${{ matrix.id }}.json"

  pr:
    needs: solve
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository + results
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Create Pull Request with all results
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: |
            Update solver results for 222-CLL (depth ${{ env.DEPTH }})
          title: Update solver results for 222-CLL
          body: |
            This PR contains the JSON outputs for all CLL_* runs at depth ${{ env.DEPTH }}.
          base: main
          branch: 222-CLL-results
          labels: solver-results
          files: |
            db/222-CLL/*.json
